name: example
description: Example for d_dialog
version: 1.0.0+1
homepage: https://github.com/dwikyhardi/custom-flutter-dialog
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  d_dialog:
    path: ".."

flutter:
  uses-material-design: true
